export const CHALLENGE_ACTIONS = {

    FETCH_PAST_CHALLENGES: 'FETCH_PAST_CHALLENGES',

    SET_PAST_CHALLENGE: 'SET_PAST_CHALLENGE',

    
    CREATE_NEW_CHALLENGE: 'CREATE_NEW_CHALLENGE',

    FETCH_USER_DATA_CURRENT_CHALLENGE: 'FETCH_USER_DATA_CURRENT_CHALLENGE',
    SET_USER_DATA_CURRENT_CHALLENGE: 'SET_USER_DATA_CURRENT_CHALLENGE',

    DELETE_USER_FROM_CURRENT_CHALLENGE: 'DELETE_USER_FROM_CURRENT_CHALLENGE',

    FETCH_ACTIVE_CHALLENGE: 'FETCH_ACTIVE_CHALLENGE',
    SET_ACTIVE_CHALLENGE: 'SET_ACTIVE_CHALLENGE',
    DELETE_ACTIVE_CHALLENGE: 'DELETE_ACTIVE_CHALLENGE'
  };