export const CHALLENGE_ACTIONS = {
    FETCH_CURRENT_CHALLENGE: 'FETCH_CURRENT_CHALLENGE',
    FETCH_PAST_CHALLENGES: 'FETCH_PAST_CHALLENGES',
    SET_CURRENT_CHALLENGE: 'SET_CURRENT_CHALLENGE',
    SET_PAST_CHALLENGE: 'SET_PAST_CHALLENGE',
    CREATE_NEW_CHALLENGE: 'CREATE_NEW_CHALLENGE'
  };